### ISSUE TITLE
v0.6.1 - Removed Admin Dashboard Template, will only be available as site in its own repository.

### ISSUE THREAD

**Issue by tmarkdriedger** [MudBlazor/Templates#122]
Is there a location where the Admin Dashboard Template is available?

**Comment by Matthewsre** [comment]
@tmarkdriedger , I was looking for the same thing and found the template is still available if you switch to tag v0.6.0. I too am also curious where this will be available going forward.

**Comment by Garderoben** [comment]
> Is there a location where the Admin Dashboard Template is available?

When its done, i will post it in discord and DOCS news etc.

**Comment by ekjuanrejon** [comment]
Any feedback on this

**Comment by raisircl** [comment]
I am following this https://www.youtube.com/watch?v=ZdSqkCRXSsw but i did not found admin dashboard

**Comment by timdriedger** [comment]
> I am following this https://www.youtube.com/watch?v=ZdSqkCRXSsw but i did not found admin dashboard

Use the [v.0.6.0](https://github.com/MudBlazor/Templates/releases/tag/v0.6.0) release.

**Comment by ScarletKuro** [comment]
Hi,

Closing this ticket. MudBlazor is not going to provide an admin dashboard anymore. If anyone wants to play with it, here is the URL: https://mudblazorwithjwt.azurewebsites.net/personal/dashboard.
If someone wants the source code, it's here: https://github.com/TheDayIsMyEnemy/BlazorTemplates/tree/admin-dashboard.
Keep in mind it's old code and unsupported. Grab it while it's still available.
