### ISSUE TITLE
Wrong casing in launchsettings?

### ISSUE THREAD

**Issue by danielwertheim** [MudBlazor/Templates#123]
Not up to speed with templating, but the launchsettings.json for `wasm` doesn't become replaced with project name.

Not sure if it's a casing issue `"Mudblazor.Template" != "MudBlazor.Template"`: https://github.com/MudBlazor/Templates/blob/a0ce58333a2631ea60c02b5c6eb23bdb3f4d9e2c/src/.template.base/wasm/Properties/launchSettings.json#L19

**Comment by Garderoben** [comment]
We have new template now with .NET 8 #448
