### ISSUE TITLE
Unable to install Mudblazor Templates

### ISSUE THREAD

**Issue by shoebsd31** [MudBlazor/Templates#124]
![image](https://user-images.githubusercontent.com/5415085/161773386-04d7e9e4-4d3c-4668-ba8e-5b3fda667792.png)
![image](https://user-images.githubusercontent.com/5415085/161773497-f30fbc19-f8f3-4e89-8078-980390bb9c1e.png)

I have created a new Blazor app with .Net 6.0, but I am not able to install Mudblazor templates. It gives me an error :
**Package 'MudBlazor.Templates 0.6.1' has a package type 'Template' that is not supported by project**

**Comment by JonBunator** [comment]
How did you install it? Did you follow the installation instructions:
```bash
dotnet new --install MudBlazor.Templates
dotnet new mudblazor --host wasm --name MyApplication
```

**Comment by shoebsd31** [comment]
> How did you install it? Did you follow the installation instructions:
> 
> ```shell
> dotnet new --install MudBlazor.Templates
> dotnet new mudblazor --host wasm --name MyApplication
> ```

I used nuget package manager to install it

**Comment by JonBunator** [comment]
Did you install it in an existing project? If so that doesn't work of course.
Nevertheless try to do it via command line

**Comment by shoebsd31** [comment]
> Did you install it in an existing project? If so that doesn't work of course. Nevertheless try to do it via command line

Thanks for the quick reply, yes I was trying to do it on an existing project
