### ISSUE TITLE
Issue with hosting on AWS Amplify

### ISSUE THREAD

**Issue by W2K** [MudBlazor/Templates#16]
I am trying to deploy your awesome template on AWS Amplify. I am using this tutorial to for that https://swimburger.net/blog/dotnet/how-to-deploy-blazor-webassembly-to-aws-amplify

For pure Blazor Wasm it works fine, as well as for pure MudBlazor template. But on your template I get web assembly exception when navigating from login to Dashboard. Same when navigating to any other page. Am I missing something is there any difference or change in hosting redirects I need to make ?

Here is the hosted example:https://dev.d2p39p1v1zkoec.amplifyapp.com/

**Comment by porkopek** [comment]
Maybe this is a hint? I don't know what causes it, though
![image](https://user-images.githubusercontent.com/13745954/123677105-a30b5b80-d83c-11eb-8226-7d8bdea63344.png)
