### ISSUE TITLE
BlazorHybrid template

### ISSUE THREAD

**Issue by Not-That-Guy** [MudBlazor/Templates#18]
Anything special we need to do to get this working with the blazorhybrid template?

I followed the standard installation details for mudblazor:
https://mudblazor.com/getting-started/installation

but made adjustments as per the syncfusion blog post about setting up on the hybrid template.
https://www.syncfusion.com/blogs/post/blazor-hybrid-apps-using-mobile-blazor-bindings.aspx

![image](https://user-images.githubusercontent.com/28390532/120914267-9b3e1880-c6cf-11eb-9474-75efa9019f17.png)

**Comment by Dunce001** [comment]
you need to remove the semi-colon

**Comment by Not-That-Guy** [comment]
> you need to remove the semi-colon

Yes that was a bit amateur, but still no joy.

**Comment by Garderoben** [comment]
What is Blazor Hybrid? :_S

**Comment by frasza** [comment]
Hey @Garderoben, what is the status and priority on MAUI template? Are we waiting for MAUI or can the template be done for preview version? Much appriciated.

**Comment by LinuxCode96** [comment]
hello, the MAUI template is already there?
