### ISSUE TITLE
Publish to NuGet?

### ISSUE THREAD

**Issue by IvanJosipovic** [MudBlazor/Templates#2]
Any plans on publishing this template on NuGet?

This will allow us to run dotnet new -i "MudBlazor.Templates::*"

See docs for more info, https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#packing-a-template-into-a-nuget-package-nupkg-file

**Comment by henon** [comment]
Great idea Ivan. Do you want to help with that?

**Comment by mikes-gh** [comment]
Great idea 👍

**Comment by saddamhossain** [comment]
This is awesome. Thanks, MudBlazor team!

**Comment by fiyazbinhasan** [comment]
I published a similar kind of package yesterday, https://www.nuget.org/packages/GeekHour.AspNetCore.MudBlazor.Templates/
Repo - https://github.com/fiyazbinhasan/MudBlazorTemplates

Great to see you guys have a plan for this 😃 🚀

**Comment by Garderoben** [comment]
Its coming!

https://user-images.githubusercontent.com/10367109/135731134-6413943e-23e2-45b3-a222-9ae70a222135.mp4
