### ISSUE TITLE
"/getting-started/templates" Page doesn't exist

### ISSUE THREAD

**Issue by Ralms** [MudBlazor/Templates#23]
On the sample website.
In the get Getting Started > Installation page (https://mudblazor.com/getting-started/installation), there is a note about pre-configured templates, with a link to https://mudblazor.com/getting-started/templates.

This templates link is returning 404. 
![image](https://user-images.githubusercontent.com/1717049/126912188-ddd5a28b-f0e6-4296-8b7a-ffaa504b4319.png)

**Comment by mckaragoz** [comment]
Now it works.

**Comment by Ralms** [comment]
> Now it works.

Don't know why you say that, the link still doesn't work.

To clarify, broken link in question is: 
![image](https://user-images.githubusercontent.com/1717049/134091583-ffd276a7-8a31-4e2d-9c26-b01afe822137.png)

**Comment by mckaragoz** [comment]
It fixed, it works on dev.mudblazor.com, and will work on website after next release.

**Comment by Ralms** [comment]
@mckaragoz thank you for the clarification and looking into it.
