### ISSUE TITLE
Please provide information about how to use these templates

### ISSUE THREAD

**Issue by Cmohan** [MudBlazor/Templates#24]
I tried packing them with nuget and installing them, but that didn't work. I tired creating a template via Visual Studio, but only the individual projects ever show up, not the solution, as a new project option. I'm left with just coping the the solution file and the folders when I want to make a new project, but that seems like a very inefficient way to use these templates.

**Comment by Garderoben** [comment]
> I tried packing them with nuget and installing them, but that didn't work. I tired creating a template via Visual Studio, but only the individual projects ever show up, not the solution, as a new project option. I'm left with just coping the the solution file and the folders when I want to make a new project, but that seems like a very inefficient way to use these templates.

Yeah the nuget and install is not working, i accepted a PR that i tought would fix it but it dident. Havent had time to look into it yet sorry.

**Comment by Garderoben** [comment]
@Cmohan done look at the readme.

**Installation**
```
dotnet new --install MudBlazor.Templates
```
**Usage**
```
dotnet new mudblazor --host wasm --name MyApplication
```
