### ISSUE TITLE
Two Radio Button and a Text Input

### ISSUE THREAD

**Issue by whann0205** [MudBlazor/Templates#28]
What is the easiest way to combine a Text Input and a Radio ButtonGroup (2 Choices) 
on the same line for targetting mobile devices (=sm breakpoints)?
I know they are several ways with css to do so but
what is the "mudblazor" way ?

**Comment by Garderoben** [comment]
@whann0205 you posted in the wrong repo :)
https://github.com/MudBlazor/MudBlazor
