### ISSUE TITLE
Mudtable a button inside and Selection

### ISSUE THREAD

**Issue by whann0205** [MudBlazor/Templates#29]
I have a mudtable linked to a ICollectionList:

<MudTable Elevation=10 Height="200px" Items="@deprULs" T="DeprUL" @bind-SelectedItem="TabSelectedItem" Hover="true" FixedHeader="true" Breakpoint="Breakpoint.None" ReadOnly="true" Dense="true">

and mapped to a var TabSelectedItem. If i click on a row on any of the table´s column the row 
gets selected and that specific row is in TabSelectedItem. 

Inside that table i have also created a button 
<MudTd><MudIconButton Icon="@Icons.Material.Outlined.Calculate" Color="MudBlazor.Color.Primary" OnClick="StartCalc"> </MudIconButton></MudTd>

Problem here is that if i click that button the row does not get selected and TabSelectedItem remains
null;

Question: How do it get the selected row into TabSelectedItem?
Do i need to manually select the row and how is that possible?

**Comment by Garderoben** [comment]
@whann0205 you posted your issue in the wrong repo.
https://github.com/MudBlazor/MudBlazor
