### ISSUE TITLE
[Windows] 404 for MudBlazor on Production mode

### ISSUE THREAD

**Issue by seriouz** [MudBlazor/Templates#30]
The MudBlazor Files could not be fetched from the aspnet backend 404:
![image](https://user-images.githubusercontent.com/4722613/134060951-d32bb7c2-9f9b-4f8f-9b4a-001769c61e11.png)

Steps to reproduce:
- Have Windows (10)
- Install dotnet 6 rc1 sdk x64
- `dotnet new blazorserver`
- Follow the tutorial: https://mudblazor.com/getting-started/installation#manual-install
- `dotnet run --environment Production`

After this easy steps i get this strange behavior (see Screenshot). It seems MudBlazor could not be served from the virtual `_content` folder.

Edit: When i'm running  `dotnet run --environment Development` everthing is fine.

**Comment by dengyakui** [comment]
I have the same problem. have you already resolved it?
I wonder If the authors are maintaining the issues.
