### ISSUE TITLE
Error.cshtml references Bootstrap

### ISSUE THREAD

**Issue by nfeltch** [MudBlazor/Templates#41]
The Error.cshtml file references the now removed ~/css/bootstrap/bootstrap.min.css and ~/css/app.css files.  Would be nice to have these use MudBlazor css classes to keep some styling.

**Comment by Mr-Technician** [comment]
This is still an issue looking at the dev branch: https://github.com/MudBlazor/Templates/blob/dev/src/.template.base/server/Pages/Error.cshtml

**Comment by abgenullt** [comment]
Are there any plans to fix this?

**Comment by Garderoben** [comment]
We have new template now with .NET 8 #448
