### ISSUE TITLE
Bug: starup error when My ASPNETCORE_ENVIRONMENT is not setting to Development

### ISSUE THREAD

**Issue by dengyakui** [MudBlazor/Templates#44]
## Bug desc
In our project,  we have multi environment configs, each of them has a appsettings file.for example:
- appsettings.json    (common config info for all env)
- appsettings.2020test.json  ( some special configs for 2020test env)
- appsettings.2020prod.json  ( some special configs for 2020prod env)

When I change the default ASPNETCORE_ENVIRONMENT to custom name, like "2020test" the MudBlazor got some error after start the project.
![image](https://user-images.githubusercontent.com/3945919/139174852-97cf3380-b697-473f-89f9-5388380f7520.png)

## My Configs
os: win11
IDE: VS2022 Version 17.0.0 Preview 4.1
local dotnet version : 5.0 latest /6.0 RC2
local MudBlazor version:   5.1.5  + lastest rc

![image](https://user-images.githubusercontent.com/3945919/139173969-405fb805-da71-47e0-8165-dd0863cb8273.png)

-------------------------------

## How to reproduce
1. Create a startup Blazor Server project using the MudBlazor template
![image](https://user-images.githubusercontent.com/3945919/139173354-6bff6323-4165-4ac1-b361-f54a7c593b85.png)

2. Open the launch setting file, change the env name from Development to a custome env
![image](https://user-images.githubusercontent.com/3945919/139173509-bc046aec-3d39-467d-8a15-490cb2343a24.png)

3. Start the server project, when the browser launch, the UI is a crazy large icon!
![image](https://user-images.githubusercontent.com/3945919/139173653-b563a73b-cf86-4ba8-a1af-18114558fc9b.png)

some static file was 404 when start not as a dev environment.
![image](https://user-images.githubusercontent.com/3945919/139173790-9e834235-4b45-48c9-86ce-5abd08942ad2.png)

**Comment by JonBunator** [comment]
You need to include:
`webBuilder.UseStaticWebAssets();`
in your `program.cs`. Then it should work

**Comment by JonBunator** [comment]
We should also add this to the templates

**Comment by psijkof** [comment]
The PR was closed, but this issue persists.
Also for WASM when hosted.

PR created:

https://github.com/MudBlazor/Templates/pull/133
