### ISSUE TITLE
Unable to install templates in VS2019 or VS2022 dotnet5 or dotnet6 to Blazor Server or Blazor WASM

### ISSUE THREAD

**Issue by beefydog** [MudBlazor/Templates#65]
Can't seem to install templates of any version.  Is there a specific project type or dependencies that must be installed to use the templates? (besides MudBlazor)
An example of the error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Package 'MudBlazor.Templates 0.1.6' has a package type 'Template' that is not supported by project 'MudBlazorTest'.

**Comment by Garderoben** [comment]
Please test again i just updated to 0.6.0 (if you use VS 2022 or rider, vscode etc)
dotnet new --install MudBlazor.Templates::0.6.0
