### ISSUE TITLE
Live Demo website down

### ISSUE THREAD

**Issue by chrome-brutus** [MudBlazor/Templates#67]
[https://templates.mudblazor.com/](https://templates.mudblazor.com/) doesn't seem to be working anymore.

**Comment by JoseHuertasDev** [comment]
Has been down from a few days

**Comment by JoseHuertasDev** [comment]
Is this still alive ?

**Comment by Jacko1394** [comment]
Still down, someone please fix 😢

**Comment by JonBunator** [comment]
@Garderoben shut them down intentionally. There will come a replacement soon

**Comment by JoseHuertasDev** [comment]
You are doing a good job!

**Comment by agustinbishel** [comment]
Hi! any news about this?

**Comment by kevinvenclovas** [comment]
Hmmm

**Comment by Garderoben** [comment]
Prob late feburary.
