### ISSUE TITLE
Where to get the Admin Dashboard template?

### ISSUE THREAD

**Issue by alexvazquez** [MudBlazor/Templates#98]
Hi, Where can I get the Admin Dashboard template?

Thanks a lot

**Comment by JonBunator** [comment]
Seems like @Garderoben removed it. But you can checkout an old commit

**Comment by alexvazquez** [comment]
Thanks a lot. Do you know why it was removed?
    On Thursday, February 10, 2022, 12:01:45 PM CST, Jonas B. ***@***.***> wrote:  
 
 


Seems like @Garderoben removed it. But you can checkout an old commit

**Comment by Garderoben** [comment]
> Thanks a lot. Do you know why it was removed? On Thursday, February 10, 2022, 12:01:45 PM CST, Jonas B. ***@***.***> wrote: Seems like @Garderoben removed it. But you can checkout an old commit — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

I removed it as it states in release notes. I will upload the new MudDashboard to its own repository when its finished, but it will no longer be part of this or any other blazor template and just be a repo with a Blazor Application inside as a demo.
